// <auto-generated />
using Enterprise.Manager.EnterpriseDB;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enterprise.Manager.Migrations
{
    [DbContext(typeof(EnterpriseFirebirdContext))]
    [Migration("20250406150819_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("Enterprise.Manager.EnterpriseDB.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("BLOB SUB_TYPE TEXT")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Email")
                        .HasColumnType("BLOB SUB_TYPE TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasColumnType("BLOB SUB_TYPE TEXT")
                        .HasColumnName("FIRSTNAME");

                    b.Property<string>("LastName")
                        .HasColumnType("BLOB SUB_TYPE TEXT")
                        .HasColumnName("LASTNAME");

                    b.Property<string>("Mobile")
                        .HasColumnType("BLOB SUB_TYPE TEXT")
                        .HasColumnName("MOBILE");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEES");
                });
#pragma warning restore 612, 618
        }
    }
}
